### ISSUE TITLE
Visiting citygram.nyc results in fatal failure

### ISSUE THREAD

**Issue by JamesCropcho** [codeforamerica/citygram#162]
Hey all,

This seems critical to me, but I'll let you decide, of course. Here's the gist:

```
james@laptop:~$ curl -I www.citygram.nyc
HTTP/1.1 301 Moved Permanently
Server: Cowboy
Connection: keep-alive
Date: Wed, 18 Feb 2015 19:04:45 GMT
Status: 301 Moved Permanently
Content-Type: text/html
Location: https://www.citygram.nyc/
X-Xss-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
Via: 1.1 vegur

james@laptop:~$ curl -I citygram.nyc
curl: (6) Could not resolve host: citygram.nyc
james@laptop:~$ 
```

Hoping to Help,
James

**Comment by bigfleet** [comment]
Hi, James.  We certainly need to provide better problem report mechanisms within the application (as I've referenced here with the link to #161) but I don't have standing to help with NYC's independent install.  It also appears to be working once more.  Thanks for the note!
