### ISSUE TITLE
Links are prefixed with an extra 'http://' in email digest

### ISSUE THREAD

**Issue by eeeschwartz** [codeforamerica/citygram#172]
![screen shot 2015-03-02 at 10 29 29 am](https://cloud.githubusercontent.com/assets/428684/6443787/6b5d0f28-c0c7-11e4-89cd-4feac5c8bad4.png)

**Comment by bigfleet** [comment]
This is what I'm seeing in the database.  Did /can you deploy citygram/citygram-services@25d261f0b992f3f2634f83324b8266c98553102e ?  Is that related at all?

**Comment by eeeschwartz** [comment]
@bigfleet definitely related. And I retroactively added 'http://' to Lexington events in Citygram which may be the issue </badpractice>. I'll take a look. The issue may be at the data level.

**Comment by eeeschwartz** [comment]
@bigfleet the issue was indeed at the data level. Thanks for taking a look but it's officially `</my bad>`
