### ISSUE TITLE
Finer grained SMS unsubscribe

### ISSUE THREAD

**Issue by bigfleet** [codeforamerica/citygram#173]
First off, you can only SMS unsubscribe everything at once (REMOVE).  To unsubscribe any one particular one, you have to browse back in your history (if it's available) to find the link you were first messaged.

Any ideas for how this can be done?  I have to do something here for the City of Charlotte.  They liked the idea of sending an instruction every week on how to unsubscribe from that feed.  I think that could get super noisy, and instead like the concept of every 25 messages or so.

Could we institute HELP and make it a list of subscriptions with their appropriate links (including second click to unsub)?

Any feedback from the broader community?

**Comment by migurski** [comment]
Conversational UI, like “no more _____” texts from users?

**Comment by bigfleet** [comment]
This describes a scheme to send informational texts

Every day at 4pm EST
  For our text message subscriptions
  Determine an 'evaluation_date' -- the later of the date the subscription was created and the date the last informational text was delivered
  If the evaluation_date is not at least two weeks ago, no informational text is needed.
  Determine the number of events this subscription has notified them of since the evaluation date
  If the number is above 28, send an informational text.

An informational text should read:

"Since July 14, 2015 we've sent you 29 Citygrams about Rezoning in Charlotte.  For more information, or to unsubscribe, click here: [link]"

Some subscriptions get bunches of texts every day, most go ages never receiving one.  This is a way to balance signal and noise.  The noisiest we get is an additional text every two weeks if you've been receiving two messages a day anyway.  We are always either less noisy or take much longer than two weeks (but never more than 30 messages) to allow you to unsub.

What say you all?

**Comment by masonpackard** [comment]
Seems pretty reasonable to me.  Allows a subtle followup with relatable / pertinent information, as well as another option for unsub.  May also give another opportunity to increase engagement of the application.

:+1:
