### ISSUE TITLE
Multiple/duplicate collision reports delivered via text alert

### ISSUE THREAD

**Issue by jooltman** [codeforamerica/citygram#174]
I recently subscribed to CityGram, and every day I get text alerts for collisions near my house.  It seems like each daily digest sends the same collision twice?  The duplicates do not feed into my text stream in the same order as they first appear, if that helps.

**Comment by bigfleet** [comment]
Thanks for your report.  It's a challenging time to respond to issues like this, but can you share your city and the general parameters of the feed you are subscribed to?

**Comment by jooltman** [comment]
Sure.

I'm in NYC and I did a mile radius for collision reports around my home.

Hope that helps.

Best,
Joanna 

Brevity/typos courtesy of iPhone

**Comment by dirkkelly** [comment]
@bigfleet I'm here in NYC with Joanna, going to take care of this.
