### ISSUE TITLE
Cary Citygram Instance

### ISSUE THREAD

**Issue by rcampbellnc** [codeforamerica/citygram#180]
The Cary Brigade has setup a portal here:  (using the OpenDataSoft platform)
https://codeforcary.opendatasoft.com/explore/dataset/police-incidents-cary
Weekly updates are made to this dataset.
A GeoJSON export is available here:
https://codeforcary.opendatasoft.com/explore/dataset/police-incidents-cary/download/?format=geojson&timezone=America/New_York

Requesting help in spinning a Cary instance of Citygram using this dataset.

**Comment by bigfleet** [comment]
@rcampbellnc Here's a thread to help get you (or a dev team) briefed.

https://github.com/codeforamerica/citygram/wiki/Getting-Started-with-Citygram

That document describes creating a connector from scratch.  Your team may find it more appealing to fork this repository https://github.com/citygram/citygram-services and copy one of the examples here: https://github.com/citygram/citygram-services/tree/master/lib/spy_glass/registry 

I have looked at the GeoJSON that your system emits.  It does need at least one amendment: incident_number must be restated as the event id.  Check for the term "Citygram compliant" here: https://github.com/codeforamerica/citygram/wiki/Getting-Started-with-Citygram#develop

Second, is there a reason that you'd like to host your own Citygram, as opposed to using citygram.org?

**Comment by rcampbellnc** [comment]
@bigfleet Thanks!! We'll dive into this.  Sorry about any confusion, we don't necessarily want a local instance of Citygram, having one at citygram.org would be great!  Any local instance would be so we could have a non-production model at this point, possibly looking to contribute additional functionality needed by our community.

**Comment by bigfleet** [comment]
@rcampbellnc Is there anything I can do to help (either with the code, or with the community)?

**Comment by rcampbellnc** [comment]
@bigfleet Sorry for taking so long -- I've gotten some help here within our Code for Cary org, could I send someone your way to collaborate on this and get it running?
I'll send to your CfA account.  THANKS!!

**Comment by bigfleet** [comment]
I committed to write up the final onboarding instructions for @rcampbellnc during the week to come.

**Comment by bigfleet** [comment]
@rcampbellnc Here's the process for going live!  https://github.com/codeforamerica/citygram/wiki/Going-Live

**Comment by bigfleet** [comment]
We are [partially live](https://www.citygram.org/triangle) here.  There is an issue on the front-end preventing addresses from being encoded correctly.  Help wanted!

**Comment by rcampbellnc** [comment]
OK Jim - How about this - Let's go for Cary as the city for now, same data endpoint - that will get us going and we can figure out how to fix this.  Does that work?

**Comment by bigfleet** [comment]
@beetz12 You can take a look at this if you like!

**Comment by beetz12** [comment]
@bigfleet, I found the issue and I've developed a solution. Basically, because Triangle is not a city, it is an invalid locality so google map api is not returning data. My solution is to append the Triangle, NC to the address field and now everything is working. Please take a look at my PR and let me know if you have any question. Thanks!

**Comment by rcampbellnc** [comment]
@beetz12 Sounds great! Is there a sandbox? Or is there some place that one of our local Brigade can see how to deploy a sandbox so we can help too?  Looking forward to seeing this working!!

**Comment by beetz12** [comment]
@rcampbellnc I'm not sure about the sandbox, but I'm sure Jim will take care of you guys. I'm excited for you guys see the working version. Thanks for being patient!

**Comment by bigfleet** [comment]
@rcampbellnc The Triangle region is now live.  I think you'd do well to find a different header image, but it's available!
