### ISSUE TITLE
No Reports for Wednesdays

### ISSUE THREAD

**Issue by rar624** [codeforamerica/citygram#181]
I'm signed up to get the weekly email with crashes in NYC. It seems that the report provides information for Thursday - Wednesday. But since the report goes out Wednesday morning, crashes that happen on Wednesday afternoons never get included in the reports.

**Comment by bigfleet** [comment]
@rar624 The code in question is here: https://github.com/codeforamerica/citygram/blob/master/app/models/event.rb#L17-18

I'm not sure how the Wednesday afternoon events are escaping.  How are you diagnosing their absence?

**Comment by dirkkelly** [comment]
I think I understand how this occurred. The publishers were updating at midday, the digest are sent out Wednesday morning (note this is a manual process currently). 

<img width="876" alt="screen shot 2015-07-19 at 6 52 10 pm" src="https://cloud.githubusercontent.com/assets/81055/8768263/74e6bcae-2e47-11e5-979f-8bcc8ad2faf7.png">

This meant that Monday feeds were never published, they were out of date on send, and updated after the send.

Thanks for the report @rar624 changed to publisher updates at 7am.

<img width="665" alt="screen shot 2015-07-19 at 6 53 45 pm" src="https://cloud.githubusercontent.com/assets/81055/8768267/865fa2c0-2e47-11e5-8f44-d92d259614f8.png">

**Comment by bigfleet** [comment]
Going to trust @dirkkelly on this one!
