### ISSUE TITLE
Email not being sent!

### ISSUE THREAD

**Issue by eeeschwartz** [codeforamerica/citygram#183]
I hadn't been receiving the weekly digests so I dove into the email to see wat wuz up.

Upon signing up for a new topic I did not receive an email confirmation. The following suspicious message appeared in the logs, originating from sendgrid I reckon:

> "535 Authentication failed: Bad username / password", "error_class"=>"Net::SMTPAuthenticationError"

Perhaps it has something to do with a recent sendgrid upgrade.

![screenshot 2015-05-20 19 47 02](https://cloud.githubusercontent.com/assets/428684/7739031/37d9d9f6-ff29-11e4-8202-b3a62cb631f4.png)

**Comment by bigfleet** [comment]
![facepalm](http://38.media.tumblr.com/tumblr_m92loceMTI1rnbtnv.gif)

Since Code for America is in charge of the billing for this app (and hence, manager of the add ons) I will locate and extinguish this flame this afternoon.

**Comment by bigfleet** [comment]
I was able to fix this on my own.  The app [doesn't use Heroku's Sendgrid variables directly](https://github.com/codeforamerica/citygram/blob/master/app/services/channels/email.rb#L13-14), so when they updated those values, email broke.  I updated the config, and have received an email that the app sent.  Service should be restored.

Also, I need to subscribe to something via email myself to make sure I can serve canary duty myself in the future.

**Comment by migurski** [comment]
For a useful canary, can I recommend adding a [status endpoint for Engine Light](http://engine-light.codeforamerica.org)?

**Comment by eeeschwartz** [comment]
@bigfleet thanks for sorting out the issue!

**Comment by bigfleet** [comment]
Can you refile that, Mike?

Cheers,

Jim
