### ISSUE TITLE
Miami JS error: "Uncaught TypeError: Cannot read property 'geometry' of undefined"

### ISSUE THREAD

**Issue by ErnieAtLYD** [codeforamerica/citygram#230]
To replicate:
1. Go to https://citygram.herokuapp.com/miami - I am using Chrome OSX v47
2. Enter `400 NW 26th Ave` in the address form

EXPECTED: marker to show up on map
ACTUAL: no marker, silent JS error in the console saying `Uncaught TypeError: Cannot read property 'geometry' of undefined`

**Comment by bigfleet** [comment]
This error occurs when the address is provided without selecting a publisher.

Several Citygram cities have only one publisher.  In this case, it seems reasonable to pre-select that publisher to prevent this error?  Alternatively, the user could be prompted to select a publisher from the list.

Silently erroring on the console can certainly be improved on.  What do you think @beetz12?

**Comment by beetz12** [comment]
@bigfleet I agree we should not silently error in the console. The user should definitely get a notification of some kind. These are some options we can try.

1. The easiest way is to pre-select the publisher for the user. But the downside is, if there are multiple publishers, the default publisher may not be what the user wants, and the user will need to re-select a different publisher after he performs the search. 
2. A better option is to prompt the user to select the publisher as soon as he clicks into the address field. This will ensure that the user selects the correct publisher first time. However, it will require an extra prompt to correct a mistake the user has made, making the process more complex. 
3. The best solution is to guide the user into making the desired selection with as little thinking as possible. One way to achieve this, we can hide the address section before the user has selected a publisher. This way, it is completely natural to the user, and we also ensure a publisher is always selected. 

@bigfleet @masonpackard What do you guys think?

**Comment by bigfleet** [comment]
I'd like to see the third choice.   If there's a sense of "This is the first of three steps", even better.

**Comment by beetz12** [comment]
@bigfleet Could you please take a look at my PR?
https://github.com/codeforamerica/citygram/pull/234

**Comment by bigfleet** [comment]
Love how this turned out, closing.
