### ISSUE TITLE
https://www.citygram.org/subscriptions returns 500 server error

### ISSUE THREAD

**Issue by bcipolli** [codeforamerica/citygram#237]
Not sure if this is related to https://github.com/codeforamerica/citygram/pull/236 ; I see it for San Diego & miami.

I chose a city, chose a notification type, skipped adding an address, and entered my email address. When I click "subscribe":
* No error is shown.
* In the console, I see: "bad request" for https://www.citygram.org/subscriptions
* When I open https://www.citygram.org/subscriptions in the browser, I get a 500 server error.

Expected behavior:
* If there's an error, catch it and show it to me (as a user).
* https://www.citygram.org/subscriptions should work :)

**Comment by bigfleet** [comment]
@bcipolli This is the next PR, make sure to actually click on the 'select' button in code enforcement before proceeding.  (This PR will make sure that you do this before you can put in an address.)

**Comment by bcipolli** [comment]
Thanks! I will close, then.
