### ISSUE TITLE
sort city names in dropdown

### ISSUE THREAD

**Issue by bcipolli** [codeforamerica/citygram#238]
While I love San Diego being on top, it'd be more intuitive (for me) to have the cities ordered alphabetically.

![image](https://cloud.githubusercontent.com/assets/4072455/12039950/9e6aa7dc-ae19-11e5-94f9-c9d902710024.png)

**Comment by bigfleet** [comment]
@bcipolli They are displayed in the order in cities.geojson, if you'd like to fix this yourself.  I am pondering a "type your zip" style interface since it's becoming so crowded up there!  (This would also allow me to track zips where Citygram isn't currently.)

**Comment by bcipolli** [comment]
Cool. Please assign the issue to me, and I'll try to fix this when I can! I'm thinking that, rather than ordering `cities.geojson` (which gets modified in PRs), I'd sort by whatever code is reading that file--which I'll figure out!

**Comment by bigfleet** [comment]
@bcipolli I am (embarrasingly) not an admin on codeforamerica/citygram, an item we will get straightened away next month.  You need to have standing on this repo before I can assign it to you (which I cannot grant you).  So lame, I know, but what can we do?  Perhaps create an issue on your fork and assign it there?

**Comment by bcipolli** [comment]
Oh, that's fine. It's in the text of the comment, so others should know that I'm planning to work on it :)

**Comment by invisiblefunnel** [comment]
@bigfleet You should be an admin now :).
