### ISSUE TITLE
Add support for planning data for RTP

### ISSUE THREAD

**Issue by dsummersl** [codeforamerica/citygram#250]
So far Adam and I have found the planning data for [Durham's GIS source here](GET //ArcGIS/rest/services/DurhamMaps/DevCases/MapServer/0/query?geometry=%7B%22ymax%22%3A921388.0377604166%2C%22xmax%22%3A2228921.275173611%2C%22ymin%22%3A750608.9622395834%2C%22xmin%22%3A1874322.724826389%7D&f=json&outFields=OBJECTID%2CA_NUMBER%2CA_TYPE%2CA_DATE%2CA_STATUS%2CA_STATUS_DATE%2CA_PROJECT_NAME%2CA_DESCRIPTION%2CA_USER_ID%2CA_CASE_PLANNER%2CStatCode%2CAppStatus%2CAppCode%2CAppType%2CCasePlanner%2CEMAIL%2CORIG_FID&returnGeometry=true&outSR=4326 HTTP/1.1
Host: gisweb2.durhamnc.gov
Connection: close
User-Agent: Paw/2.3 (Macintosh; OS X/10.11.3) GCDHTTPRequest
).

@adamajm you have some links for Cary and Raleigh?

**Comment by T300M256** [comment]
I have them up. Here you go:

Raleigh: https://data.raleighnc.gov/category/urban-planning

Cary: https://data.townofcary.org/explore/?refine.theme=Spatial+planning,+Town+planning,+Buildings,+Equipment,+Housing&sort=modified

BTW, your Durham link is dead or malformed.

**Comment by dsummersl** [comment]
Sorry about that. [Here is a working link](http://gisweb2.durhamnc.gov//ArcGIS/rest/services/DurhamMaps/DevCases/MapServer/0/query?geometry=%7B%22ymax%22%3A921388.0377604166%2C%22xmax%22%3A2228921.275173611%2C%22ymin%22%3A750608.9622395834%2C%22xmin%22%3A1874322.724826389%7D&f=json&outFields=OBJECTID%2CA_NUMBER%2CA_TYPE%2CA_DATE%2CA_STATUS%2CA_STATUS_DATE%2CA_PROJECT_NAME%2CA_DESCRIPTION%2CA_USER_ID%2CA_CASE_PLANNER%2CStatCode%2CAppStatus%2CAppCode%2CAppType%2CCasePlanner%2CEMAIL%2CORIG_FID&returnGeometry=true&outSR=4326)
