### ISSUE TITLE
Charlotte Rezoning Digest URLs Incorrect

### ISSUE THREAD

**Issue by ekerstein** [codeforamerica/citygram#258]
Take the example below. The rezoning digest shows:

http://charmeck.org/city/charlotte/planning/Rezoning/RezoningPetitions/2016Petitions/Pages/2016-136.aspx

However this is redirected to the charlottenc.gov main page. The correct URL should be:

http://charlottenc.gov/planning/Rezoning/RezoningPetitions/2016Petitions/Pages/2016-136.aspx

![screen shot 2016-09-18 at 6 07 51 pm](https://cloud.githubusercontent.com/assets/6055508/18619453/e41f5468-7dca-11e6-9eda-5344a82a714d.png)

**Comment by ekerstein** [comment]
Looks like maybe somebody fixed it? Seems to be working now.

**Comment by bigfleet** [comment]
It bre
