### ISSUE TITLE
One-click Unsubscribe in email not working

### ISSUE THREAD

**Issue by hannahbkates** [codeforamerica/citygram#260]
Hey Citygram Team! I've tried unsubscribing from the 311 Service Requests email several times, but the emails keep coming. Each time I click the One-click Unsubscribe link, I get the confirmation page, but the request isn't actually being processed.

**Comment by bigfleet** [comment]
In the past this has happened when there were multiple subscriptions.  Can you post an obfuscated email you signed up with, and we can remove it on our side?

**Comment by hannahbkates** [comment]
hannahbkates ( at ) g mail - Thank you!
