### ISSUE TITLE
Geocoding service to locate addresses isn't working. 

### ISSUE THREAD

**Issue by aplannersguide** [codeforamerica/citygram#264]
I am unable to enter an address and have the system geocode the location. As a result, users can no longer create new city gram alerts. I'm also wondering if existing alerts are affected by this as well.

**Comment by bigfleet** [comment]
@aplannersguide I couldn't duplicate this on Chrome OS X-- can I get more info?

**Comment by aplannersguide** [comment]
It is working now. I swear it wasn't. I'm closing this out and hoping it was just a weird google geocoding glitch.
