### ISSUE TITLE
Add Orlando Voting

### ISSUE THREAD

**Issue by flyinactor91** [codeforamerica/citygram#274]
We're waiting on the citygram-services PR to go through and a logo to be made as well, but this will add voting center notifications for Orlando

```
Publisher.create! do |pub|
  pub.title = "Elections"
  pub.endpoint = "https://citygram-services.herokuapp.com/orlando-voting-centers"
  pub.active = true
  pub.visible = true
  pub.city = "Orlando"
  pub.icon = "voting.png"
  pub.state = "FL"
  pub.description = "Voting reminders for Orange County. Leadup notifications with your polling location"
  pub.tags = ["orlando","orl","voting","election"]
end
```

We will also need the defunct OPD service which was added in #254 removed when this publisher is added

**Comment by bigfleet** [comment]
@flyinactor91 I've merged that PR and added this data to the database.  It'll get polled.  Until the logo is available, I've marked it as not visible.  When the logo PR lands, I'll flip the visibility and availability of the Orlando datasets.

**Comment by flyinactor91** [comment]
PR #281 has been made. Added four icons for others to use as well

**Comment by flyinactor91** [comment]
We're still waiting for the database to be updated to enable the voting service and delete OPD Reports
