### ISSUE TITLE
Los Angeles Data Feed

### ISSUE THREAD

**Issue by tonyomendoza** [codeforamerica/citygram#292]
Hello,

Thank you for merging our branch. The city is not showing up as a selection nor are there any topics being shown for our city. Is there anything else we are supposed to do on our end?

Thank you

**Comment by tonyomendoza** [comment]
Thank you @bigfleet 

I believe the next step is to add the datasets. I created four sets of console incantations here:
https://gist.github.com/tonyomendoza/5c485bb4673ab549e0a8c707d2671d08

I have also pasted four incantations below.

```
Publisher.create! do |pub|
  pub.title = "Building Permits"
  pub.endpoint = "https://citygram-los-angeles-registry.herokuapp.com/los-angeles-building-permits"
  pub.active = true
  pub.visible = true
  pub.city = "Los Angeles"
  pub.icon = "building-permits.png"
  pub.state = "CA"
  pub.description = "Los Angeles"
  pub.tags = ["los-angeles"]
end
```

```
Publisher.create! do |pub|
  pub.title = "LAX Road Closures"
  pub.endpoint = "https://citygram-los-angeles-registry.herokuapp.com/los-angeles-lax-road-closures"
  pub.active = true
  pub.visible = true
  pub.city = "Los Angeles"
  pub.icon = "cone.png"
  pub.state = "CA"
  pub.description = "Los Angeles"
  pub.tags = ["los-angeles"]
end
```

```
Publisher.create! do |pub|
  pub.title = "Metro (Bus)"
  pub.endpoint = "https://citygram-los-angeles-registry.herokuapp.com/los-angeles-metro"
  pub.active = true
  pub.visible = true
  pub.city = "Los Angeles"
  pub.icon = "la/bus.png"
  pub.state = "CA"
  pub.description = "Los Angeles"
  pub.tags = ["los-angeles"]
end
```

```
Publisher.create! do |pub|
  pub.title = "Metro Rail"
  pub.endpoint = "https://citygram-los-angeles-registry.herokuapp.com/los-angeles-metro-rail"
  pub.active = true
  pub.visible = true
  pub.city = "Los Angeles"
  pub.icon = "la/train.png"
  pub.state = "CA"
  pub.description = "Los Angeles"
  pub.tags = ["los-angeles"]
end
```

I have reviewed the go-live description. If there is anything I missed, I will keep a lookout.
Thank you again for your help!

**Comment by tonyomendoza** [comment]
Thank you for adding our city to the list @bigfleet !! 
We noticed there is an Internal Internal Server Error for the page. Is there anything we are missing?

**Comment by bigfleet** [comment]
The ball is still in my court.  I’ll update the ticket when it’s working.  Strange times for Citygram!

**Comment by JoseantonioMaciel** [comment]
Thank you @bigfleet !!

**Comment by bigfleet** [comment]
@tonyomendoza I had to tweak some of your incantations-- your icons were committed to the repository with slightly different names and paths than the above, and that's why you had an error on the page for a little while, even though the data was collecting.  Citygram should be live in LA!

**Comment by tonyomendoza** [comment]
Thank you @bigfleet !!
Looks like that’s my fault, I’ll have to fix those icon paths for next time. Thank you!
