### ISSUE TITLE
Cannot register after entering in address possibly due to geocode API

### ISSUE THREAD

**Issue by qtrandev** [codeforamerica/citygram#294]
I am getting the error "Unable to geocode city. Womp Womp." in the console log when I enter in an address. I tried with https://www.citygram.org/miami but I also checked Los Angeles and see the same issue.

I searched for the error and it pointed to here:
https://github.com/codeforamerica/citygram/blob/b2c1faa513c570cf19a5da1aa8dcbd314cba7755/app/assets/js/scripts.js#L358

The geocoding API used is:
https://maps.googleapis.com/maps/api/geocode/json?address=

Google started charging to use their Maps-related services and also imposed rate limits even with an API key. (https://developers.google.com/maps/documentation/javascript/geocoding)

An alternative geocoding API might need to be considered. (Nominatim maybe)
Thanks for looking into this issue!

**Comment by bigfleet** [comment]
@qtrandev Thanks so much for reporting this.  @jszwedko are you experiencing similar?

**Comment by jszwedko** [comment]
@bigfleet we had built our own front-end so aren't relying on the one built-in to Citygram, but notably, we did register a Google API key for the front-end geocoding there.

**Comment by AndrewNatoli** [comment]
Can confirm this issue also exists for Charlotte. Requests to geocode an address come back from Google Maps denied because they're missing an API key.

```
{
   "error_message" : "You must use an API key to authenticate each request to Google Maps Platform APIs. For additional information, please refer to http://g.co/dev/maps-no-account",
   "results" : [],
   "status" : "REQUEST_DENIED"
}
```

Also checked with Austin--- the same issue exists with entering an address in order to register. Austin's map can show events though. I _might_ be touching on two separate issues here?

**Comment by qtrandev** [comment]
Closing since this issue looks fixed to me. Checked Miami and Los Angeles city sites.
