### ISSUE TITLE
Setup engine light

### ISSUE THREAD

**Issue by invisiblefunnel** [codeforamerica/citygram#64]

**Comment by dirkkelly** [comment]
For future reference https://github.com/codeforamerica/engine-light

**Comment by bigfleet** [comment]
Example controller: https://github.com/codeforamerica/cityvoice/blob/master/app/controllers/status_controller.rb

* Consider which services to declare as dependencies (all publishers?) and add the controller
* Register that url

**Comment by masonpackard** [comment]
**Here is the request:**
http://localhost:5000/status

**Results:**
{"status":"ok","dependencies":["postgres","twilio"],"updated":1438124024}

**Comment by masonpackard** [comment]
Updated Status for engine light to be outside of the API and simply return json.

**Request:**
http://localhost:5000/status

**Results:**
{"status":"ok","dependencies":["postgres","twilio"],"updated":1438124453}
