### ISSUE TITLE
display message when trying to subscribe with invalid input

### ISSUE THREAD

**Issue by cainejette** [codeforamerica/citygram#89]
Right now, clicking subscribe with invalid input does nothing to inform the user what went wrong.

Possible invalid input include: no/invalid address, no/invalid phone.

Also, it looks like "find me" feature fails silently if you haven't selected a citygram topic.

**Comment by dirkkelly** [comment]
fwiw this has been worked on in master.

![screen shot 2015-02-04 at 8 39 51 pm](https://cloud.githubusercontent.com/assets/81055/6053491/0048ca88-acae-11e4-8e38-8eaaaad27198.png)

**Comment by bigfleet** [comment]
@dirkkelly I think this enough to close it, what say you?
